trigger:
  branches:
    include:
      - main # 👈 Fix list formatting
jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest' # 👈 Proper indentation
    steps:
      - script: |
          pip install -r requirements.txt
          python -m pytest tests/
        displayName: 'Run tests'
